#!/usr/bin/env python3
"""LoWS plan-status guard (Plan 05 companion) — deterministic, ZERO LLM tokens.

Makes each plan's `status:` (and optional `priority:`) frontmatter the single source of truth so
Plans/README's boards and Plans/CHANGELOG can't silently rot. Jobs:

  HARD (non-zero exit): every Plans/NN_*.md has a valid `status:` (proposed|in-progress|done|superseded);
         any `priority:` is one of now|next|later.
  BOARD: regenerates TWO auto-blocks in Plans/README.md (never hand-edited):
         • the full status board (all plans, by number);
         • the 🎯 Next up board (OPEN plans that carry a `priority:`, ordered now→next→later).
  ADVISORY (warn): a `done` plan not in Plans/CHANGELOG.md; a closed plan still carrying a `priority:`;
         no open plan prioritized at all.

Usage:
  python3 scripts/check_plans.py           # regenerate the boards (run after changing a status/priority)
  python3 scripts/check_plans.py --check    # verify only — fail if a board is stale; never writes
                                            #   (this is what verify.sh / pre-commit call)
"""
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PLANS = REPO / "Plans"
README = PLANS / "README.md"
CHANGELOG = PLANS / "CHANGELOG.md"

VALID = {"proposed", "in-progress", "done", "superseded"}
OPEN = {"proposed", "in-progress"}
BADGE = {"proposed": "📋 proposed", "in-progress": "🚧 in-progress", "done": "✅ done", "superseded": "⤴️ superseded"}
PRIORITY_ORDER = {"now": 0, "next": 1, "later": 2}
PRIORITY_BADGE = {"now": "🔴 now", "next": "🟡 next", "later": "⚪ later"}

START, END = "<!-- AUTOGEN:status-board:start -->", "<!-- AUTOGEN:status-board:end -->"
NEXT_START, NEXT_END = "<!-- AUTOGEN:nextup:start -->", "<!-- AUTOGEN:nextup:end -->"
NOTE = "_Auto-generated from each plan's `status:` frontmatter by `scripts/check_plans.py` — do not edit by hand._"
NEXT_NOTE = ("_The live \"what to tackle next\" list — OPEN plans that carry a `priority:` (now|next|later), "
             "auto-generated by `scripts/check_plans.py`. To reorder: edit a plan's `priority:` frontmatter; "
             "clear it (or set `status: done`) when finished._")


def parse_fm(text: str) -> dict:
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    fm = {}
    for line in text[3:end].splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            fm[k.strip()] = v.strip()
    return fm


def h1_scope(text: str) -> str:
    for line in text.splitlines():
        if line.startswith("# "):
            t = line[2:].strip()
            m = re.match(r"Plan\s+\d+\s*[—–-]\s*(.*)", t)
            return (m.group(1).strip() if m else t)
    return ""


def build_board(rows) -> str:
    lines = ["| Plan | Status | Scope |", "|------|--------|-------|"]
    for name, st, scope in rows:
        lines.append(f"| [{name}]({name}) | {BADGE[st]} | {scope} |")
    return f"{START}\n{NOTE}\n\n" + "\n".join(lines) + f"\n{END}"


def build_nextup(items) -> str:
    """items: list of (name, status, priority, scope) — OPEN plans with a priority, any order."""
    if not items:
        body = "_Nothing prioritized yet — add `priority: now|next|later` to an open plan's frontmatter._"
        return f"{NEXT_START}\n{NEXT_NOTE}\n\n{body}\n{NEXT_END}"
    items = sorted(items, key=lambda x: (PRIORITY_ORDER[x[2]], x[0]))
    lines = [f"- {PRIORITY_BADGE[pri]} — [{name}]({name}) · {BADGE[st]} — {scope}"
             for name, st, pri, scope in items]
    return f"{NEXT_START}\n{NEXT_NOTE}\n\n" + "\n".join(lines) + f"\n{NEXT_END}"


def _sub_block(text, start, end, block, label, errors):
    """Replace the start…end region with `block`. If the markers are missing, record an error and no-op."""
    if start in text and end in text:
        return re.sub(re.escape(start) + r".*?" + re.escape(end), lambda _: block, text, flags=re.DOTALL)
    errors.append(f"Plans/README.md is missing the {label} markers ({start} … {end})")
    return text


def main(argv):
    check_only = "--check" in argv
    plans = sorted(PLANS.glob("[0-9]*.md"))
    errors, warns, rows, nextup = [], [], [], []

    for p in plans:
        text = p.read_text(encoding="utf-8")
        fm = parse_fm(text)
        st = fm.get("status")
        if st not in VALID:
            errors.append(f"{p.relative_to(REPO)} → missing/invalid status: {st!r} (allowed: {sorted(VALID)})")
            continue
        scope = h1_scope(text)
        if st == "superseded" and fm.get("superseded_by"):
            scope += f" — superseded by Plan {fm['superseded_by']}"
        rows.append((p.name, st, scope))

        pri = fm.get("priority")
        if pri is not None:
            if pri not in PRIORITY_ORDER:
                errors.append(f"{p.name} → invalid priority: {pri!r} (allowed: now|next|later, or omit)")
            elif st not in OPEN:
                warns.append(f"{p.name} is {st} but still carries priority:{pri} — clear it (it can't be 'next')")
            else:
                nextup.append((p.name, st, pri, scope))

    # regenerate (or verify) both README auto-blocks
    rtext = README.read_text(encoding="utf-8")
    new = _sub_block(rtext, START, END, build_board(rows), "status-board", errors)
    new = _sub_block(new, NEXT_START, NEXT_END, build_nextup(nextup), "nextup", errors)
    if new != rtext:
        if check_only:
            errors.append("Plans/README.md boards are STALE — run `python3 scripts/check_plans.py` to regenerate")
        else:
            README.write_text(new, encoding="utf-8")
            print("📋 regenerated Plans/README.md boards (status + 🎯 next up)")

    # advisories
    clog = CHANGELOG.read_text(encoding="utf-8") if CHANGELOG.exists() else ""
    for name, st, _ in rows:
        if st == "done":
            num = name[:2]
            if f"Plan {num}" not in clog and f"Plan {int(num)}" not in clog:
                warns.append(f"{name} is done but not in CHANGELOG.md — add a milestone line")
    if not nextup:
        warns.append("no open plan has a priority: — set priority: now|next|later to populate the 🎯 Next up board")

    print(f"📋 check_plans: scanned {len(rows)} plans ({len(nextup)} prioritized)")
    if errors:
        print(f"\n❌ {len(errors)} issue(s):")
        for e in errors:
            print(f"   • {e}")
    if warns:
        print(f"\n⚠️  {len(warns)} advisory:")
        for w in warns:
            print(f"   • {w}")
    if not errors and not warns:
        print("✅ plans healthy — boards current, all done plans logged.")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
